In [0]:
import tensorflow as tf

In [0]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
from keras.layers import Dropout

Using TensorFlow backend.


In [0]:
df=pd.read_csv('bank.csv')

In [0]:
df.head()

RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [0]:
X=df.iloc[:,3:13].values
y=df.iloc[:,13].values

In [0]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
labelencoder_X_1=LabelEncoder()
X[:,1]=labelencoder_X_1.fit_transform(X[:,1])
labelencoder_X_2=LabelEncoder()
X[:,2]=labelencoder_X_2.fit_transform(X[:,2])

In [0]:
X

array([[619, 0, 0, ..., 1, 1, 101348.88],
       [608, 2, 0, ..., 0, 1, 112542.58],
       [502, 0, 0, ..., 1, 0, 113931.57],
       ...,
       [709, 0, 0, ..., 0, 1, 42085.58],
       [772, 1, 1, ..., 1, 0, 92888.52],
       [792, 0, 0, ..., 1, 0, 38190.78]], dtype=object)

In [0]:
X[[0]]

array([[619, 0, 0, 42, 2, 0.0, 1, 1, 1, 101348.88]], dtype=object)

In [0]:
onehotencoder=OneHotEncoder(categorical_features=[1])
X=onehotencoder.fit_transform(X).toarray()

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_encoders.py:451: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [0]:
X=X[:,1:]

In [0]:
X[[0]]

array([[0.0000000e+00, 0.0000000e+00, 6.1900000e+02, 0.0000000e+00,
        4.2000000e+01, 2.0000000e+00, 0.0000000e+00, 1.0000000e+00,
        1.0000000e+00, 1.0000000e+00, 1.0134888e+05]])

In [0]:
from sklearn.model_selection import train_test_split
seed = 1
test_size = 0.3
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=test_size, random_state=seed)

In [0]:

from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.fit_transform(X_test)

In [0]:
import keras
model=tf.keras.models.Sequential()

In [0]:
model.add(tf.keras.layers.Dense(6,activation='relu'))

W0706 14:23:43.379864 140244766902144 deprecation.py:506] From /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/init_ops.py:1251: calling VarianceScaling.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


In [0]:
model.add(tf.keras.layers.Dense(6,activation='relu'))

In [0]:
model.add(tf.keras.layers.Dense(1,activation='sigmoid'))

In [0]:
sgd_optimizer=tf.keras.optimizers.SGD(lr=0.03)
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [0]:
model.fit(X_train,y_train,
          validation_data=(X_test,y_test),
          epochs=30,
          batch_size=10)

W0706 14:23:43.544852 140244766902144 deprecation.py:323] From /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/nn_impl.py:180: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


Train on 7000 samples, validate on 3000 samples
Epoch 1/30
7000/7000 [==============================] - 1s 166us/sample - loss: 0.5951 - acc: 0.7023 - val_loss: 0.4663 - val_acc: 0.7937
Epoch 2/30
7000/7000 [==============================] - 1s 142us/sample - loss: 0.4413 - acc: 0.8120 - val_loss: 0.4358 - val_acc: 0.8120
Epoch 3/30
7000/7000 [==============================] - 1s 145us/sample - loss: 0.4252 - acc: 0.8211 - val_loss: 0.4284 - val_acc: 0.8143
Epoch 4/30
7000/7000 [==============================] - 1s 141us/sample - loss: 0.4178 - acc: 0.8237 - val_loss: 0.4215 - val_acc: 0.8190
Epoch 5/30
7000/7000 [==============================] - 1s 140us/sample - loss: 0.4077 - acc: 0.8277 - val_loss: 0.4104 - val_acc: 0.8230
Epoch 6/30
7000/7000 [==============================] - 1s 138us/sample - loss: 0.3899 - acc: 0.8383 - val_loss: 0.3873 - val_acc: 0.8380
Epoch 7/30
7000/7000 [==============================] - 1s 140us/sample - loss: 0.3703 - acc: 0.8490 - val_loss: 0.3690 - va

In [0]:
y_pred=model.predict(X_test)
y_pred=((y_pred>0.5))

In [0]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_test,y_pred)

In [0]:
cm

array([[2282,   91],
       [ 314,  313]])

In [0]:
accuracy_score(y_test,y_pred)

0.865